import Head from "next/head";
import { GetStaticProps } from "next";
import { Layout, MovieCard } from "../components";
import { getMoviesData, Movie } from "../lib/movies";

export default function Home({ moviesData }: { moviesData: Movie[] }) {
  return (
    <div className="bg-gray-100">
      <Layout home>
        <Head>
          <title>Cinemapp</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className="text-xl text-gray-800 pt-10">
          <ul className="list-none p-0 m-0">
            {moviesData.map((movie: Movie) => (
              <li className="m-0 mb-5" key={movie.id}>
                <MovieCard {...movie} />
              </li>
            ))}
          </ul>
        </section>
      </Layout>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const moviesData = await getMoviesData();
  return {
    props: {
      moviesData,
    },
  };
};
