import Head from "next/head";
import { Layout } from "../components";

export default function Home() {
  return (
    <Layout home>
      <Head>
        <title>Cinemapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="mt-6"></section>
      <section className="text-xl text-gray-800 pt-1">
        <ul className="list-none p-0 m-0"></ul>
      </section>
    </Layout>
  );
}
